config/routes.rb
Rails.application.routes.draw do  

  devise_for :users
  resources :users, only: [:show] do 
	resources :items, only: [:create, :destroy]
  end

  get 'welcome/index'
  get 'welcome/about'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  def days_left
  	7 - (DateTime.now.to_date - self.created_at.to_date).to_i
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :items
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  	user_path(@user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!

  def create
  	#@user = User.find(params[:user_id])
  	@user = current_user
  	@item = @user.items.new(item_params)
  	if @item.save
  	  flash[:notice] = "Item was created."
  	   redirect_to user_path(@user) # user show page
  	else
  	  flash[:error] = "Error saving item. Please try again."
  	end
  end

  def destroy
  	#@user = User.find(params[:user_id])
  	@user = current_user
  	@item = @user.items.find(params[:id]) 
  	if @item.destroy
  	  flash[:notice] = "Item was deleted."
  	else
  	  flash[:error] = "Error deleting item. Please try again."
  	end
  	respond_to do |format| 
  	  format.html { redirect_to user_path(@user) }
  	  format.js 
  	end 	
  end

private
  def item_params
  	params.require(:item).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
  #	@user = User.find(params[:id])
  	@user = current_user
  	@items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def class_type(index)
	 case index 
	      when "success" then "alert alert-success" # green
	      when "info" then "alert alert-info"       # blue
	      when "notice" then "alert alert-info"     # blue
	      when "warning" then "alert alert-warning" # yellow
	      when "alert" then "alert alert-warning"   # yellow
	      when "danger" then "alert alert-danger"   # red
	      when "error" then "alert alert-danger"    # red
	    end
	  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h4>Create new todo</h4>

<%= form_for [@user, Item.new] do |f| %>
  <div class="col-md-8">

    <div class="form-group">
	  <%#= f.label :name, "Item" %>
	  <%= f.text_field :name, class: "form-control", placeholder: "Enter your todo item" %>
  	</div>

    <div class="form-group">
  	  <%= f.submit class: "btn btn-default" %>
    </div>

  </div>

<% end %>

app/views/items/_item.html.erb
<tbody id="item-<%= item.id %>">
	<tr>
		<td ><%= item.name %></td>
		<td><%= item.days_left %></td>
		<td><%= link_to "", user_item_path(item.user, item), method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
		<%#= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok' %>
	</tr>
</tbody>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  //$('#item-<%#= @item.id %>').hide(); // this style works also
  $('#item-' + <%= @item.id %>).fadeOut(500);
<% else %>
   $('#item-' +<%= @item.id %>).append("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplifyTodo</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">
  </head>

  <body class="background-image">

  	<div class='container'>

  	  	<%= render 'shared/navbar' %>

        <%= render 'shared/flash' %>

  	    <%= yield %>

	   </div>

  </body>

</html>

app/views/shared/_flash.html.erb
<%# flash[:success] = "This is a test message" %>

<% flash.each do |index, message| %>
	<!-- <div class="alert alert-<%= index %>">  -->
	<div class="<%= class_type(index) %>">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= message %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default background-2">
  <div class="container-fluid">

    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Todos", user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "About", welcome_about_path %></li>

    </ul>

    <ul class="nav navbar-nav navbar-right user-info">
    	<%# if current_user %> <!-- ok to use also -->
      <% if user_signed_in? %>
        <div class="signed-in">
          Hello <%= link_to(current_user.name || current_user.email, edit_user_registration_path) %> ! &nbsp; 
        	<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
          </div>
        <% else %>
	        <li><%= link_to "Sign Up", new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
	        <li><%= link_to "Sign In", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
	    <% end %>
    </ul>

  </div>
</nav>

app/views/users/show.html.erb
<div class="container">
  <div class="rows">

	<h1><%= @user.name %>'s Todo List</h1>
	<%#= mail_to @user.email %>
	<% if @user.items.any? %>

		<table class="table table-hover js-todos">
			<thead>
		      <tr>
		        <th>Description</th>
		        <th>Days left</th>
		        <th>Complete</th>
		      </tr>
	    	</thead>			
			
			<%= render partial: 'items/item', collection: @items %>
			
		</table>

	<% end %>
	
		<%= render partial: 'items/form', locals: { user: @user } %>

  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to Simpl!fy Todo</h1>
<p>To use this simple todo app you need to be signed in and confirmed.</p>
<p>You can create as many todo items as you want.</p>
<p>Only the signed user will have view and access to your account.</p>
<p>You will have 7 days to finish your todo.</p>
<p>Once you click complete it will delete your todo.</p>

app/views/welcome/index.html.erb
<div class="jumbotron jumbotron-fluid background-2" >
  <div class="container">

    <h1 class="display-3 display-title">Simpl!fy Todo</h1>
    <p class="lead display-paragraph">A self-destruting to-do list to keep you focused on the things that really matter.</p>

  </div>
</div>